In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
car = pd.read_csv('quikr_car.csv')

In [4]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
car.shape

(892, 6)

In [6]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [7]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [8]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [9]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

Quality
- names are pretty inconsistent
- names have company names attached to it
- some names are spam like 'Maruti Ertiga showroom condition with' and 'Well mentained Tata Sumo'
- company: many of the names are not of any company like 'Used', 'URJENT', and so on.
- year has many non-year values
- year is in object. Change to integer
- Price has Ask for Price
- Price has commas in its prices and is in object
- kms_driven has object values with kms at last.
- It has nan values and two rows have 'Petrol' in them
- fuel_type has nan values

# Cleaning

In [10]:
car = car[car['year'].str.isnumeric()]

In [11]:
car['year'] = car['year'].astype(int)

In [12]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int32
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int32(1), object(5)
memory usage: 42.8+ KB

In [13]:
car = car[car['Price'] != "Ask For Price"]

In [14]:
car['Price']

0        80,000
1      4,25,000
3      3,25,000
4      5,75,000
6      1,75,000
         ...
886    3,00,000
888    2,60,000
889    3,90,000
890    1,80,000
891    1,60,000
Name: Price, Length: 819, dtype: object

In [15]:
 car['Price'] = car['Price'].str.replace(',', '').astype(int)

In [16]:
car['kms_driven']

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [17]:
car['kms_driven'] = car['kms_driven'].str.split(' ').str.get(0).str.replace(',', '')

In [18]:
car = car[car['kms_driven'].str.isnumeric()]

In [19]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.3+ KB

In [20]:
car['kms_driven'] = car['kms_driven'].astype(int)

In [21]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [22]:
car = car[~car['fuel_type'].isna()]

In [23]:
car['name'] = car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [24]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [25]:
car = car.reset_index(drop = True)

In [26]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [27]:
car.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [28]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int32
 3   Price       816 non-null    int32
 4   kms_driven  816 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 28.8+ KB

In [29]:
car[car['Price'] > 6e6]

                   name   company  year    Price  kms_driven fuel_type
534  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [30]:
car = car[car['Price'] < 6e6].reset_index(drop = True)

In [31]:
car.to_csv('Cleaned Car.csv')

# Model

In [32]:
X = car.drop(columns = 'Price')

In [33]:
y = car['Price']

In [34]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [35]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [37]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [38]:
ohe = OneHotEncoder()
ohe.fit(X[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [39]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [40]:
column_trans = make_column_transformer((OneHotEncoder(categories = ohe.categories_), ['name', 'company', 'fuel_type']),
                                      remainder = 'passthrough')

In [41]:
lr = LinearRegression()

In [42]:
pipe = make_pipeline(column_trans, lr)

In [43]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [44]:
y_pred = pipe.predict(X_test)

In [45]:
r2_score(y_test, y_pred)

0.5145494873266827

In [46]:
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    print(r2_score(y_test, y_pred), i)

0.5499897471686866 0
0.5155423684050942 1
0.6931519716663607 2
0.656639078369843 3
0.5325384985760214 4
0.6203940950559284 5
0.6194386686890169 6
0.6127927128839735 7
0.6024009528956153 8
0.5192830583140662 9
0.6183228392986377 10
0.6092308960745281 11
0.5276874910382623 12
0.5180339601607105 13
0.7818746718814149 14
0.6718501388983944 15
0.7270328674846481 16
0.6203168579046585 17
0.5969262173458663 18
0.3809568226530412 19
0.6848160525141884 20
0.5471792638273658 21
0.6175135929361197 22
0.6888356229796418 23
0.7368859807672217 24
0.5011454447269331 25
0.6610112178375325 26
0.5854877325983954 27
0.6188515438899735 28
0.5408231850140145 29
0.5691041827248104 30
0.7276232830689098 31
0.5418005571748475 32
0.722008600549789 33
0.5658131019056793 34
0.5763199223890407 35
0.5790935715059401 36
0.6403986888013042 37
0.5711307602202251 38
0.6825621690854198 39
0.7053214728255051 40
0.678510974657663 41
0.7314695626532096 42
0.6797450728238621 43
0.6703938936103668 44
0.8079666708172052 45
0.7822225777466153 46
0.7720982703811783 47
0.7198593865535841 48
0.6137386170429566 49
0.42853642902566924 50
0.5089165178068842 51
0.6921885073549635 52
0.6566280520493426 53
0.7660427610675598 54
0.5904870681106897 55
0.5928811433248439 56
0.6933307668235762 57
0.6487031382422165 58
0.7300564791979198 59
0.7015455986048916 60
0.7369304651896151 61
0.6736796900120843 62
0.6384951353819939 63
0.577651021793024 64
0.7205398530110496 65
0.5282019557227227 66
0.6717583824761297 67
0.5819240968891707 68
0.6715170692699982 69
0.7054525717754754 70
0.43561589246339505 71
0.4928117339875574 72
0.5854755467139721 73
0.6604114295299477 74
0.6865136960379885 75
0.6385942410317775 76
0.6633403961251061 77
0.5998447566365808 78
0.6500712484558291 79
0.5399285517139152 80
0.6844731739291738 81
0.5964656260535364 82
0.6328635045926445 83
0.5758410185619744 84
0.6887505991404801 85
0.6131705350185649 86
0.5823607512824505 87
0.5773064796663454 88
0.7386841033937107 89
0.4748143405771309 90
0.5835514610658392 91
0.6483631457242303 92
0.6862672574031472 93
0.754032599880533 94
0.6361084086766728 95
0.724708167555109 96
0.5556526331111629 97
0.8236381592805935 98
0.614468577619538 99
0.6764783182734032 100
0.7936675184165218 101
0.684524819752556 102
0.47625379763309217 103
0.54739241383997 104
0.5501434934083302 105
0.5741838312043843 106
0.7107212162072756 107
0.7093193711951755 108
0.4354580868915322 109
0.717938000878747 110
0.7051477028083367 111
0.6262014001586464 112
0.7348368676077118 113
0.45065125326411626 114
0.7035805864425841 115
0.6582744965372714 116
0.5527943119677763 117
0.7356075851508665 118
0.5413246387288748 119
0.6931463154428321 120
0.6803719599264952 121
0.6870245032120704 122
0.6703409961371508 123
0.6415829428374066 124
0.5895739623867016 125
0.549173897981396 126
0.7056971751138001 127
0.6976734793657506 128
0.7246270523766283 129
0.45184383781977533 130
0.54114975349162 131
0.626129436736178 132
0.5728760627890295 133
0.6157360566668777 134
0.654148900603525 135
0.6581712731663155 136
0.6799758803902778 137
0.6969922882459734 138
0.7237210969514755 139
0.6937658116255969 140
0.6302616040979487 141
0.5988279727212515 142
0.5132058927996164 143
0.713642629763793 144
0.6776862794479055 145
0.6188107454139937 146
0.63378143426289 147
0.6649080285586328 148
0.6567691974769653 149
0.72124656882867 150
0.740783305295746 151
0.6478041843366412 152
0.5257747302399638 153
0.7174489554492745 154
0.6599439499669706 155
0.6635048323265158 156
0.6699288404931045 157
0.5692852877095537 158
0.7090538261887842 159
0.5472706679414225 160
0.5972313004723333 161
0.6104021801033286 162
0.6782681439414768 163
0.6896885896502408 164
0.6850564889596844 165
0.6273314668493425 166
0.5343578184666631 167
0.6281311907280476 168
0.6037867730142652 169
0.7318580474868568 170
0.7046431946485987 171
0.6539490300518843 172
0.6011849929085747 173
0.5890658080441057 174
0.4803821926095341 175
0.625756155107734 176
0.6668426073872744 177
0.611655677508072 178
0.6724068456609125 179
0.6492514335534223 180
0.7380634745994427 181
0.7087005346605689 182
0.5543905269286453 183
0.6769061557179604 184
0.7299931289338766 185
0.743567466383829 186
0.5125529061480559 187
0.7605406307151529 188
0.6752167721705086 189
0.7291660552237611 190
0.7335675897271872 191
0.5665458770433824 192
0.5333093761778124 193
0.7140918973629389 194
0.816100793177544 195
0.44040554428040557 196
0.6449426729388872 197
0.6026977703691135 198
0.6298593907055587 199
0.7481285089809634 200
0.6689040903026149 201
0.723598621208687 202
0.7257713339293949 203
0.6774498056253733 204
0.7151910782782833 205
0.5599300690768896 206
0.6310394263649595 207
0.5265395889208926 208
0.6719158440053892 209
0.7407829209137367 210
0.49991555207713356 211
0.749236020901419 212
0.6812580895980616 213
0.7190643669203387 214
0.6464031848624905 215
0.5634111786102649 216
0.6106347293473715 217
0.5060032816673059 218
0.6273026961515225 219
0.6716073727467164 220
0.48860428745225337 221
0.6955349438678537 222
0.6356642132908701 223
0.5308485877567914 224
0.6325305567397932 225
0.5688365600372034 226
0.7001122131637654 227
0.7074782179045507 228
0.7384239007654225 229
0.6390886710281336 230
0.6960830831769541 231
0.6711463935098798 232
0.7054016143474913 233
0.6456513924620504 234
0.5727502908856354 235
0.775361720614071 236
0.67578178978924 237
0.5958518568402693 238
0.7045870648205832 239
0.7437347828444558 240
0.5894972018802844 241
0.5525757361910332 242
0.7477739869060077 243
0.6420018261454536 244
0.6916634716078895 245
0.5842453021207743 246
0.5900938147140856 247
0.6091356682211104 248
0.6525727420811315 249
0.5615298516413167 250
0.4964429567769134 251
0.6717323151170642 252
0.6404796070146221 253
0.5525325350141413 254
0.7189664528574314 255
0.5551027264551371 256
0.5102731872255124 257
0.7209619125846711 258
0.7165443347468823 259
0.6443740191285144 260
0.7307459531209367 261
0.5889120300788839 262
0.5489673579222468 263
0.6478211878023169 264
0.739366068088606 265
0.7833825545298911 266
0.715384203944936 267
0.5624989469582774 268
0.7572522784927808 269
0.6308953151963159 270
0.5493987259364947 271
0.7680437304171901 272
0.6599959218092515 273
0.6069435114054047 274
0.6130492062529576 275
0.6407611881566733 276
0.5991766306810213 277
0.6369467692594133 278
0.7079610120914112 279
0.6623308177137956 280
0.6636068850018472 281
0.7003208217672341 282
0.5920669141654049 283
0.5698224264363438 284
0.6361533333181943 285
0.5458744030850194 286
0.7337407880551146 287
0.6193676043353193 288
0.6519026739232558 289
0.6316618849215354 290
0.5664471905147983 291
0.5197218744561478 292
0.6044637897348714 293
0.7006870887968552 294
0.6337168092113015 295
0.7533288188168769 296
0.6128212594292892 297
0.72573607083107 298
0.6969332087198403 299
0.6748364267130451 300
0.6725500954929411 301
0.7235179042415839 302
0.5977800501297359 303
0.680210600576027 304
0.7400768234011033 305
0.7457340957440532 306
0.6077377331372782 307
0.5850918944888686 308
0.772781430495499 309
0.7340138148021634 310
0.6300082299166954 311
0.7282644229449697 312
0.7506332966667622 313
0.6246622880934335 314
0.7444403847248142 315
0.43494802156227974 316
0.661911340674834 317
0.7020411483336328 318
0.7612379244607697 319
0.704611566944189 320
0.46602334406178203 321
0.7387002523022553 322
0.6083558110306133 323
0.4840896462808929 324
0.6667765260564648 325
0.5247797265330822 326
0.5521589644003686 327
0.5102788048658828 328
0.5061782617964741 329
0.5160193296753703 330
0.6846369415352039 331
0.6350154556238805 332
0.5807338417898965 333
0.47159490412695904 334
0.6797673447381487 335
0.7358034979575232 336
0.7250694401841322 337
0.5899731214597028 338
0.7265972908343574 339
0.6879934727902075 340
0.653785598553319 341
0.7133245868688223 342
0.6148002090512759 343
0.6477724993919721 344
0.7633053076004948 345
0.6746806735745869 346
0.6830984265974853 347
0.515884057934467 348
0.6692478222397868 349
0.7413445068678401 350
0.5817218353518377 351
0.4930526380564708 352
0.7157092925625848 353
0.4012751020984143 354
0.49433084039939856 355
0.606311870370368 356
0.7480026849789054 357
0.634482839027324 358
0.788165864137489 359
0.6259739215586764 360
0.6865351562502611 361
0.6360224544171403 362
0.6185881421929039 363
0.661800666864804 364
0.7460449431145371 365
0.674279972681089 366
0.4626399917568119 367
0.7638929935182613 368
0.7635233187345127 369
0.5167268277803816 370
0.6564644544183145 371
0.7869548868286076 372
0.6201897564702478 373
0.7232930439712383 374
0.5513479761464538 375
0.6656334078184334 376
0.6968217192655483 377
0.5723166196946823 378
0.6824611460794114 379
0.5995646457747217 380
0.5858126949161548 381
0.5093326813680579 382
0.5379583580009308 383
0.693103312264841 384

0.7472473577196974 385
0.6732141100055773 386
0.5463631599113521 387
0.5119341175756602 388
0.6424908494633613 389
0.48615251780415314 390
0.5616154449583555 391
0.4956401962533471 392
0.7419195564569567 393
0.6578621569954135 394
0.7090419053943257 395
0.6963991495182003 396
0.7413878300594243 397
0.5569129289282595 398
0.590624713187939 399
0.5729956116614328 400
0.6686184541528022 401
0.5255213558212798 402
0.6005063547948362 403
0.4349385954978927 404
0.7308206454512702 405
0.5607125113035556 406
0.4797396619358798 407
0.642687946000865 408
0.6832467580029451 409
0.771416862613507 410
0.7405919219103838 411
0.6402085576881738 412
0.5185482094848843 413
0.6426848425101981 414
0.721032008225571 415
0.7413343875022476 416
0.7210820707399572 417
0.5434913300819064 418
0.7380888748454646 419
0.7162131446738706 420
0.626448410805788 421
0.7046617949057953 422
0.5585547639350897 423
0.5810941935998788 424
0.6276320285511654 425
0.6856146174809892 426
0.7444017879891258 427
0.6816492499602667 428
0.7673584977963143 429
0.5645793710577887 430
0.6329937511240944 431
0.6779082202536744 432
0.6721246202947053 433
0.594317623986116 434
0.5934598890807282 435
0.5529896731904503 436
0.6491635518617649 437
0.7340272799291241 438
0.6436412882329369 439
0.620635399380403 440
0.5575976414205647 441
0.7278148817992106 442
0.5657249472565296 443
0.6257413902781821 444
0.5993547836106297 445
0.672714143791405 446
0.48845440797663264 447
0.5845185695988335 448
0.5667624420000712 449
0.5064413038115287 450
0.5508983570789932 451
0.7021216654292477 452
0.5958313126213116 453
0.7253090687542869 454
0.6657064086525536 455
0.5090077142228332 456
0.6735517501415179 457
0.7104375199145485 458
0.4890733352959572 459
0.7377606514143107 460
0.6666056017628068 461
0.7507030523107887 462
0.5945380349503814 463
0.6462008396545975 464
0.5368297680499783 465
0.6527882839043317 466
0.6231393842185502 467
0.6069941299596688 468
0.5588698435555592 469
0.6214498061321522 470
0.7309218843152514 471
0.7233063245044538 472
0.5479969859982078 473
0.6150461861907053 474
0.5688318279064222 475
0.5844567383096866 476
0.7201724036567896 477
0.6197683057418082 478
0.6481233075265758 479
0.7636191708666137 480
0.6608257150262843 481
0.6806982331504361 482
0.7776728397103856 483
0.6485240412756361 484
0.6164567670650192 485
0.4860183627874557 486
0.691362985411413 487
0.473205224054261 488
0.7115615488426135 489
0.5196319582709459 490
0.591075523622878 491
0.8086212871215224 492
0.6147666533808176 493
0.6048278487966356 494
0.6204704768552423 495
0.5792207462290988 496
0.546652277694786 497
0.6980776839780356 498
0.5513853358110296 499
0.6701536290399869 500
0.6358827560282234 501
0.7719098651085732 502
0.6857994897702399 503
0.4818510706196193 504
0.744877249204962 505
0.6249458806541615 506
0.6643982457274641 507
0.6145929852778411 508
0.6477497548859588 509
0.7388469973505909 510
0.592584840497038 511
0.6399903499924682 512
0.48493403456694983 513
0.6469137881003215 514
0.6960597311162944 515
0.6215436463096646 516
0.6694764061765408 517
0.4224296247715629 518
0.6453510888297017 519
0.585277883466857 520
0.7926256430122547 521
0.5428758392945588 522
0.5856841794844071 523
0.6244102676528016 524
0.5970427892799194 525
0.7083847803599546 526
0.6104353827318545 527
0.5969843335221644 528
0.6265458515728528 529
0.7321373185106972 530
0.5747626419847592 531
0.6761582305867198 532
0.6918416681441025 533
0.7247858177555896 534
0.6461770768881789 535
0.750738956562438 536
0.675686522946646 537
0.702269474909185 538
0.654905344563725 539
0.5285692108886986 540
0.43530501967021396 541
0.7805414189044777 542
0.6407545595070872 543
0.757848937016933 544
0.5979447341539295 545
0.7371969483309109 546
0.5876305071574822 547
0.6542212548388304 548
0.6120672946768488 549
0.6325138030673406 550
0.5490042988293432 551
0.544016458021322 552
0.552776836531597 553
0.42335267265795307 554
0.6860602609978317 555
0.5793971840523806 556
0.7261484255745176 557
0.592601620865838 558
0.5299550674442903 559
0.6368161373879377 560
0.7568510351710817 561
0.7065121873849508 562
0.6728363657599556 563
0.579483318382447 564
0.5463788811225989 565
0.7559154663187044 566
0.7006946109896953 567
0.6715848802543611 568
0.7403370104906134 569
0.5510321791760422 570
0.6928786319200794 571
0.7987794870300804 572
0.6388003882091537 573
0.6405530868466133 574
0.527365103752724 575
0.645356178871378 576
0.6861965140644308 577
0.7629243146576098 578
0.524835564725598 579
0.6355387532674516 580
0.6441804478482929 581
0.6870226045936352 582
0.5741074531363881 583
0.7103337487814503 584
0.574927381293328 585
0.6288262085450486 586
0.6573242429058634 587
0.6950656999260193 588
0.6574832301811766 589
0.761578694766177 590
0.6063622559010203 591
0.7847550811597763 592
0.6256069624509544 593
0.77486112219357 594
0.6257317846148228 595
0.5729617576574477 596
0.700637977939311 597
0.7121561668823351 598
0.685672446517321 599
0.5572165821703737 600
0.7000111960715841 601
0.5587866371590766 602
0.7180586796595922 603
0.7407472781549878 604
0.7192427781477271 605
0.5680638475962072 606
0.7017019914926999 607
0.6333814089515917 608
0.6672359832654626 609
0.5655083187973298 610
0.5263849282434886 611
0.7277876482250061 612
0.6391176479904545 613
0.6399679834682913 614
0.7118713961201899 615
0.6216398391239826 616
0.5800543958738689 617
0.4540162211869577 618
0.711555172660921 619
0.6134617042273589 620
0.5553809729372614 621
0.6886467480397244 622
0.7051956014580243 623
0.5302792515703478 624
0.6671660692365258 625
0.5740959926143085 626
0.5724386909773564 627
0.6321710749647691 628
0.6669715423132567 629
0.5805194690025975 630
0.668956428887225 631
0.7697394326891135 632
0.6340139999040545 633
0.5009243197875809 634
0.5631411109901748 635
0.6007710027334774 636
0.654300322767708 637
0.7124470079340288 638
0.6907474412912048 639
0.6879147759734487 640
0.6656538312124902 641
0.6748089391657213 642
0.5697136635752746 643
0.47861733493562153 644
0.7908726770069395 645
0.5582033413592162 646
0.6470851623246088 647
0.7081685188591604 648
0.716906572258172 649
0.6478364053006052 650
0.6802877290286757 651
0.6786454081277123 652
0.6919880478742685 653
0.535946329703678 654
0.5874716759003324 655
0.6875789457792311 656
0.547565232625626 657
0.6262556676158406 658
0.5820676805765144 659
0.5384662939353546 660
0.7695362938982496 661
0.5975442280263549 662
0.6693816249235252 663
0.541822998137813 664
0.6250580460730475 665
0.7104738316930159 666
0.6059617876853189 667
0.8039610931046158 668
0.6592247349441281 669
0.7387034862891817 670
0.5791993585432451 671
0.687050758336212 672
0.7202869354068483 673
0.7221666133188509 674
0.5666352845004393 675
0.641760975995644 676
0.6763062360273651 677
0.41093264380735417 678
0.7312401618706961 679
0.706581024864082 680
0.8310728288510774 681
0.6575989282576404 682
0.5829189373796977 683
0.6477968315129098 684
0.8341928768969674 685
0.5386706708383705 686
0.6755024653970596 687
0.5856640393323 688
0.6085409932241348 689
0.6237309237693334 690
0.647621691542075 691
0.6838070868464253 692
0.5589172561955005 693
0.6640176232704643 694
0.5055118096242359 695
0.6260751920839849 696
0.74874815957808 697
0.6903813664250502 698
0.7173080140398752 699
0.5637374815084244 700
0.6260552146366145 701
0.5685703225923182 702
0.5622719298192496 703
0.6015543135437817 704
0.6025904016443345 705
0.6222711383021868 706
0.594197191778721 707
0.7458774792231229 708
0.6513049882505577 709
0.7083090455130785 710
0.5118687674029336 711
0.5642684540460617 712
0.6555509213035784 713
0.7394469848775409 714
0.623110437100943 715
0.6120890630061044 716
0.6538576623889307 717
0.6680101271995438 718
0.6091521086768072 719
0.42446421576800475 720
0.5942486300058605 721
0.6292292457928292 722
0.632333958894866 723
0.7646700835653625 724
0.5735772620252406 725
0.512037969105785 726
0.5736067265344514 727
0.5257872930177396 728
0.6510694627211877 729
0.6168629483365391 730
0.6957475683574063 731
0.7613344601048645 732
0.6608842244651806 733
0.6337168088417006 734
0.6669099135410024 735
0.6202200155877056 736
0.7339388009511882 737
0.642996909475956 738
0.6931883888746124 739
0.6824191483351316 740
0.7211873525280275 741
0.6835991833413392 742
0.6107590264365508 743
0.6702511849621984 744
0.6555455174691807 745
0.7805232477176066 746
0.5420385794716951 747

0.5502079663398145 748
0.6501894715839291 749
0.6257440725111068 750
0.7271587980551542 751
0.42777758835706015 752
0.6343299842318271 753
0.5990132228401233 754
0.5167374276723635 755
0.5229165537860931 756
0.5284666474278442 757
0.5965445415650613 758
0.6655213398285986 759
0.6852180964773449 760
0.6776773352218538 761
0.5519318471902596 762
0.6134342387511533 763
0.6186929602996245 764
0.6939945840119586 765
0.5452690223544692 766
0.669999873995696 767
0.45507246170187143 768
0.5927924814320196 769
0.7359361214708598 770
0.6758743079817027 771
0.61533540902378 772
0.6794625121364 773
0.5248146113838115 774
0.6339390046956579 775
0.6618425024394669 776
0.7142183145203858 777
0.6372930470460729 778
0.7574389494317599 779
0.734438846572516 780
0.5334778519532088 781
0.45220725425797703 782
0.6904012361593989 783
0.6462218225170105 784
0.4983173627078633 785
0.5670721357814974 786
0.5596728501103301 787
0.5213525930211151 788
0.7097112918132202 789
0.6729411130330378 790
0.6181194033124572 791
0.5823410437518811 792
0.6804007927546143 793
0.6811518039288906 794
0.6962076935227518 795
0.7316236883421747 796
0.6922709231063054 797
0.5457587592867593 798
0.6173415480677469 799
0.714755348765388 800
0.573658486742463 801
0.7390275668843275 802
0.5462708480968615 803
0.6184272728980253 804
0.7174794869494184 805
0.6404727426766696 806
0.7096550187757731 807
0.581641041919081 808
0.7056863771325816 809
0.6038064383031747 810
0.595402322611279 811
0.707546757407385 812
0.5619744794879653 813
0.56275241248394 814
0.6768253630347831 815
0.5823168355367419 816
0.5459651337598386 817
0.6677162233412425 818
0.5940862636004063 819
0.558620549511831 820
0.6606243481938663 821
0.5677673777249255 822
0.5023711193620869 823
0.6658608139882537 824
0.670980199228556 825
0.6583720735001687 826
0.5615686581722892 827
0.6995927944508977 828
0.6381658217856403 829
0.5739804020839094 830
0.7857233636048256 831
0.7393819818671787 832
0.6908968076991713 833
0.7118221459772388 834
0.4458618979774088 835
0.7050420395008861 836
0.6648835095308102 837
0.7227392361446505 838
0.7425497096883285 839
0.6970568428522976 840
0.6939264814052257 841
0.7436724886398801 842
0.6865874913997116 843
0.723577379654102 844
0.623532255756987 845
0.5816365956920226 846
0.6785545653600248 847
0.7728151417414622 848
0.6737030737502518 849
0.5635105510508851 850
0.5992513401935995 851
0.5923516293498641 852
0.6789634605562449 853
0.7473275867260862 854
0.6314785211359348 855
0.593704532187493 856
0.5649096382703105 857
0.5458274127000092 858
0.5815216821375442 859
0.6931696697760643 860
0.6403000237379319 861
0.593237965945447 862
0.6602129230900813 863
0.614500980440422 864
0.6371045036673706 865
0.6133926049105407 866
0.6466078683125367 867
0.6645740947546355 868
0.5837129118893467 869
0.6863098431236025 870
0.6389430624631012 871
0.5801854735480495 872
0.5880376298552081 873
0.7849066579278312 874
0.6247301155240044 875
0.6341527213707117 876
0.5717009119710323 877
0.610699008360782 878
0.7078540365971165 879
0.5879280096871381 880
0.7066780886491326 881
0.6478807100058167 882
0.7162685331322636 883
0.6383080286035957 884
0.6665735899311548 885
0.5752422767386236 886
0.679184893511992 887
0.5813657907527712 888
0.6557277565668636 889
0.5931620318221581 890
0.6006434678647941 891
0.6305795222461108 892
0.7726171957575075 893
0.4092963637580044 894
0.6179714633891047 895
0.6595387971716844 896
0.7167518320653326 897
0.7033410293733702 898
0.7520500346841321 899
0.680654301236717 900
0.611799663228405 901
0.6992071359193625 902
0.669540436699493 903
0.647437404975125 904
0.7174070773803927 905
0.6960111820946772 906
0.6427633004427403 907
0.6399771954606299 908
0.6645514609509201 909
0.7283266644303579 910
0.6562894104192514 911
0.6006592516173448 912
0.6043168850471625 913
0.7693456081063973 914
0.7635554180539139 915
0.6646176158556866 916
0.49889273743179763 917
0.7397801862902254 918
0.5077628478508145 919
0.6224154683982928 920
0.7052335630476021 921
0.44387106389563913 922
0.6893684131490325 923
0.640018225965644 924
0.7125219538418404 925
0.6937095945805003 926
0.5078426788586696 927
0.6412730717703083 928
0.5512594913889187 929
0.4909724301701701 930
0.5455077419461396 931
0.6568534635757527 932
0.5477379341385755 933
0.6900979794675453 934
0.6369965581931537 935
0.6585188308314244 936
0.6978658819456669 937
0.5032011281457931 938
0.7730415944489334 939
0.4877657066265826 940
0.5506125873295409 941
0.6612508640324763 942
0.6745103157019041 943
0.5469009137261747 944
0.4290959914055552 945
0.5689892842185769 946
0.6922582477243611 947
0.48725977074066895 948
0.7817949263101941 949
0.6561945929230641 950
0.650592000171537 951
0.6007584149933003 952
0.7270079131817506 953
0.7747443319163925 954
0.6310521553722712 955
0.6168076101740715 956
0.6001459020292748 957
0.7350055514043614 958
0.5306449343127891 959
0.5242305410516523 960
0.5906309703389848 961
0.7212571392762421 962
0.5243640189764295 963
0.6854886754313417 964
0.5651605600977103 965
0.6606239127847849 966
0.7023405546004333 967
0.801926789752303 968
0.6340843550894154 969
0.5882790004878227 970
0.4504293282118095 971
0.6524561320831831 972
0.712788105916021 973
0.5983833384188559 974
0.7465451402370253 975
0.5198878455914551 976
0.7147540504673418 977
0.6238560952943514 978
0.6050408600963266 979
0.6465280275858999 980
0.6577092498354362 981
0.5523602366849962 982
0.7036987640254175 983
0.7386151880069691 984
0.6170996927187454 985
0.5590291581668398 986
0.538874946396783 987
0.683795984660811 988
0.5850427581795281 989
0.6696939206913717 990
0.7093527152436008 991
0.615519480012356 992
0.6783947752677325 993
0.6800264216232974 994
0.46510269323996867 995
0.732584574539491 996
0.7447212477052191 997
0.661291144964492 998
0.43920741928458584 999

In [47]:
scores = []
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append(r2_score(y_test, y_pred))

In [48]:
np.argmax(scores)

433

In [49]:
scores[np.argmax(scores)]

0.8457042416667213

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
(r2_score(y_test, y_pred))

0.8457042416667213

In [55]:

ip.predict(pd.DataFrame(columns=['name','company','year','kms_driven','fuel_type'],data=np.array(['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']).reshape(1,5)))

NameError: name 'ip' is not defined